"""
Tabelas de domínio conforme documentação Cielo EDI v15.14.1

Este módulo contém todas as tabelas de referência para decodificação
dos códigos presentes nos arquivos Cielo EDI.
"""

from typing import Dict, Final


class TipoArquivo:
    """Tipos de arquivo Cielo EDI"""

    CAPTURA_PREVISAO: Final[str] = "03"
    LIQUIDACAO_PAGAMENTO: Final[str] = "04"
    SALDO_ABERTO: Final[str] = "09"
    NEGOCIACAO_RECEBIVEIS: Final[str] = "15"
    PIX: Final[str] = "16"


TIPOS_ARQUIVO: Final[Dict[str, str]] = {
    "03": "Captura/Previsão",
    "04": "Liquidação/Pagamento",
    "09": "Saldo em aberto",
    "15": "Negociação de Recebíveis Cielo (NRC)",
    "16": "Pix",
}

TIPOS_LANCAMENTO: Final[Dict[str, str]] = {
    "01": "Venda débito",
    "02": "Venda crédito",
    "03": "Venda parcelada",
    "04": "Ajuste a débito",
    "05": "Ajuste a crédito",
    "06": "Cancelamento de venda",
    "07": "Reversão de cancelamento de venda",
    "08": "Contestação do portador do cartão",
    "09": "Reversão de contestação do portador do cartão",
    "10": "Aluguel de máquina",
    "11": "Valor cedido em negociação",
    "13": "Débito de recebíveis dados como garantia (gravame)",
    "14": "Crédito de recebíveis dados como garantia (gravame)",
    "15": "Débito de compensação de valores em agenda financeira",
    "16": "Crédito de compensação de valores em agenda financeira",
    "17": "Devolução de crédito de valor cedido em negociação",
    "18": "Devolução de débito de valor cedido em negociação",
    "19": "Devolução de crédito de recebíveis dados como garantia (gravame)",
    "20": "Devolução de débito de recebíveis dados como garantia (gravame)",
    "23": "Débito de penhora por decisão judicial",
    "26": "Devolução de débito de penhora por decisão judicial",
    "27": "Débito de cancelamento/contestação sobre negociação cancelada",
    "28": "Crédito de cancelamento/contestação sobre negociação cancelada",
    "35": "Compensação a débito devido lançamento em garantia (gravame)",
    "36": "Compensação a crédito devido lançamento em garantia (gravame)",
    "37": "Compensação à débito devido lançamento de penhora",
    "38": "Compensação à crédito devido lançamento de penhora",
    "39": "Compensação à débito devido lançamento de cessão",
    "40": "Compensação à crédito devido lançamento de cessão",
    "42": "Venda Voucher",
}

CODIGOS_BANDEIRAS: Final[Dict[str, str]] = {
    "001": "Visa",
    "002": "Master Card",
    "003": "American Express",
    "006": "Sorocred",
    "007": "Elo",
    "009": "Diners",
    "011": "Agiplan",
    "015": "Banescard",
    "023": "Cabal",
    "029": "Credsystem",
    "035": "Explanada",
    "040": "Hipercard",
    "060": "JCB",
    "064": "Credz",
    "072": "Hiper",
    "075": "Ourocard",
    "888": "Pix",
}

STATUS_PAGAMENTO: Final[Dict[str, str]] = {
    "00": "Agendado",
    "0P": "Agendado",
    "03": "Enviado ao banco",
    "45": "Enviado ao banco",
    "54": "Enviado ao banco",
    "0O": "Enviado ao banco",
    "04": "Pago",
    "05": "Pago",
    "10": "Pago",
    "11": "Pago",
    "31": "Pago",
    "32": "Pago",
    "98": "Pago",
    "99": "Pago",
    "0A": "Pago",
    "0B": "Pago",
    "0C": "Pago",
    "0M": "Pago",
    "0N": "Pago",
    "0W": "Pago",
    "0Z": "Pago",
    "06": "Rejeitado pelo banco",
    "0R": "Rejeitado pelo banco",
    "07": "Reenviado ao banco",
    "0X": "Reenviado ao banco",
    "0Y": "Reenviado ao banco",
    "46": "Debitado em conta",
    "47": "Debitado em conta",
    "58": "Pago via negociação",
    "42": "Débito Pendente",
    "48": "Débito Pendente",
}

FORMA_PAGAMENTO: Final[Dict[str, str]] = {
    "001": "Agiplan crédito à vista",
    "002": "Agiplan parcelado loja",
    "003": "Banescard crédito à vista",
    "004": "Banescard parcelado loja",
    "005": "Esplanada crédito à vista",
    "006": "Credz crédito à vista",
    "007": "Esplanada parcelado loja",
    "008": "Credz parcelado loja",
    "009": "Elo Crediário",
    "010": "Mastercard crédito à vista",
    "011": "Maestro",
    "012": "Mastercard parcelado loja",
    "013": "Elo Construcard",
    "014": "Elo Agro Débito",
    "015": "Elo Agro Custeio",
    "016": "Elo Agro Investimento",
    "017": "Elo Agro Custeio + Débito",
    "018": "Elo Agro Investimento + Débito",
    "019": "Discover crédito à vista",
    "020": "Diners crédito à vista",
    "021": "Diners parcelado loja",
    "022": "Visa Agro Custeio + Débito",
    "023": "Visa Agro Investimento + Débito",
    "024": "FCO Investimento",
    "025": "Agro Eléctron",
    "026": "Agro Custeio",
    "027": "Agro Investimento",
    "028": "Visa FCO Giro",
    "029": "Visa crediário no crédito",
    "030": "Visa parcelado cliente",
    "031": "Pré-pago Visa Débito",
    "032": "Pré-pago Visa Crédito",
    "033": "JCB crédito a vista",
    "034": "Visa débito conversos de moeda",
    "035": "Pré-pago Visa Carnê",
    "036": "Visa Saque com cartão de Débito",
    "037": "Flex Car Visa Vale",
    "038": "Credsystem crédito à vista",
    "039": "Credsystem parcelado loja",
    "040": "Visa crédito à vista",
    "041": "Visa Eléctron Débito à vista",
    "042": "Visa Pedágio",
    "043": "Visa parcelado loja",
    "044": "Visa Eléctron Pré-Datado",
    "045": "Alelo Refeição",
    "046": "Alelo Alimentação",
    "058": "Alelo Multibenefícios",
    "059": "Alelo Auto",
    "060": "Sorocred débito à vista",
    "061": "Sorocred crédito à vista",
    "062": "Sorocred parcelado loja",
    "064": "Visa Crediário",
    "065": "Alelo Refeição",
    "066": "Alelo Alimentação",
    "067": "Visa Capital de Giro",
    "068": "Visa Crédito Imobiliário",
    "069": "Alelo Cultura",
    "070": "Elo crédito a vista",
    "071": "Elo débito à vista",
    "072": "Elo parcelado loja",
    "073": "Pré-pago Visa Cash (Visa Vale pedágio)",
    "075": "Visa Voucher",
    "079": "Pagamento Carnê Visa Eléctron",
    "080": "Visa Crédito Conversor de Moeda",
    "081": "Mastercard Crédito Especializado (*)",
    "082": "Amex crédito à vista",
    "083": "Amex parcelado loja",
    "084": "Amex parcelado banco",
    "089": "Elo Crédito Imobiliário",
    "091": "Elo Crédito Especializado (*)",
    "094": "Banescard Débito",
    "096": "Cabal crédito à vista",
    "097": "Cabal débito à vista",
    "098": "Cabal parcelado loja",
    "107": "Pré-pago Mastar Card Carnê",
    "110": "Pré-pago Mastar Card Crédito",
    "111": "Pré-pago Mastar Card Débito",
    "161": "Hiper crédito à vista",
    "162": "Hiper débito à vista",
    "163": "Hiper parcelado loja",
    "164": "Hipercard crédito à vista",
    "165": "Hipercard parcelado loja",
    "200": "Verdecard crédito a vista",
    "201": "Verdecard parcelado loja",
    "202": "Nutricash Alimentação",
    "203": "Nutricash Refeição",
    "204": "Nutricash Multibenefícios",
    "205": "Nutricash Combustível",
    "206": "Ben Alimentação",
    "207": "Ben Refeição",
    "215": "Voucher MasterCard",
    "269": "Pré-pago Elo Carnê",
    "270": "Pré-pago Elo Crédito",
    "271": "Pré-pago Elo Débito",
    "275": "Elo Multibenefícios",
    "278": "Elo Transporte",
    "282": "Pré-pago Amex Crédito",
    "314": "Ourocard Agro débito",
    "315": "Ourocard Agro custeio",
    "316": "Ourocard Agro investimento",
    "317": "Ourocard Agro custeio + débito",
    "318": "Ourocard Agro investimento + débito",
    "321": "Mastercard crediário no crédito",
    "322": "Mastercard parcelado cliente",
    "324": "Elo parcelado cliente",
    "330": "Elo crediário no crédito",
    "342": "Mastercard Pedágio",
    "377": "Elo Carnê",
    "378": "Mastercard Carnê",
    "380": "Mastercard Crédito Conversor de Moeda",
    "433": "JCB parcelado loja",
}

GRUPO_CARTOES: Final[Dict[str, str]] = {
    "00": "Serviço não atribuído",
    "01": "Cartão emitido no Brasil",
    "02": "Cartão emitido no exterior",
    "03": "MDR por tipo de cartão - Inicial",
    "04": "MDR por tipo de cartão - Intermediário",
    "05": "MDR por tipo de cartão - Superior",
}

CANAL_VENDA: Final[Dict[str, str]] = {
    "000": "Cielo Lio",
    "001": "POS (Point of Sale)",
    "002": "Mobile",
    "003": "Manual",
    "004": "URA/CVA",
    "005": "EDI/Remessa (Troca de dados)",
    "006": "GDS/IATA",
    "007": "E-commerce",
    "008": "TEF/PDV",
    "009": "Pedágio",
    "010": "Central de atendimento (BackOffice)",
    "011": "Central de atendimento",
    "012": "Chargeback",
    "013": "Ouvidoria",
    "014": "Massivo",
    "015": "Digitado",
    "099": "Não identificado",
    "   ": "Não identificado",
    "998": "Não se aplica",
}

TIPO_CAPTURA: Final[Dict[str, str]] = {
    "00": "Reentrada manual",
    "01": "Venda digitada",
    "02": "Leitura de trilha",
    "03": "Leitura de código de barra",
    "04": "Leitura ótica",
    "05": "Leitura de chip",
    "06": "Leitura de trilha",
    "07": "Contactless",
    "08": "QR Code",
    "09": "Leitura de chip",
    "10": "Venda digitada",
    "80": "Leitura de chip",
    "81": "Venda digitada",
    "82": "Leitura de chip",
    "83": "Leitura de chip",
    "90": "Leitura de trilha",
    "91": "Contactless",
    "95": "Leitura de chip",
    "99": "Tap on Phone",
}

TIPO_CARTAO: Final[Dict[str, str]] = {
    "00": "Serviço não atribuído",
    "01": "Visa Classic",
    "02": "Visa Empresarial",
    "03": "Visa Gold",
    "04": "Visa Platinum",
    "05": "Visa Infinite",
    "06": "Visa Corporate",
    "07": "Visa Electron",
    "08": "Visa Compras",
    "09": "Master Platinum",
    "10": "Master Standard",
    "11": "Master Gold",
    "12": "Master Pré-Pago",
    "13": "Master Black",
    "14": "Master Corporativo",
    "15": "Master Cartão Viagem",
    "16": "Master Cartão Benefício",
    "17": "Master World",
    "18": "Master Agro",
    "19": "Elo BNDES",
    "20": "Elo Classic",
    "21": "Elo Empresarial",
    "22": "Elo Insumos",
    "23": "Elo Corporativo",
    "24": "Elo Mais",
    "25": "Elo Grafite",
    "26": "Elo Nanquim",
    "27": "Elo Pré Pagos Geral / Gift Card",
    "28": "Elo Vale Cultura",
    "29": "Elo Nacional PJ Empresarial",
    "30": "Elo Compras",
    "31": "Elo Viagem",
    "32": "Elo Premiação Inc de Vendas PJ",
}

TIPO_PRECIFICACAO: Final[Dict[str, str]] = {
    "00000": "Não se aplica (vendas efetuadas antes da data de implantação)",
    "00001": "Aluguel",
    "00002": "Cielo Facilita",
    "00003": "Venda",
    "00012": "Dedicado",
    "00021": "TAP White label",
    "00022": "TAP Bradesco",
    "00023": "TAP Banco do Brasil",
    "00024": "Cielo TAP",
    "00026": "Conecta",
    "00032": "Venda pelo WhatsApp",
    "00033": "Link de pagamento",
    "00035": "Checkout",
    "00036": "API E-commerce",
    "00037": "BNDES",
    "00038": "Intercambio diferenciado (Vibra)",
    "00041": "IATA/EDI",
    "00045": "Agro",
    "00046": "Não se aplica",
}

TIPO_LIQUIDACAO: Final[Dict[str, str]] = {
    "000": "Não identificado",
    "001": "Débito",
    "002": "Crédito",
    "004": "Voucher",
}

# Motivos de ajuste - tabela completa conforme manual
MOTIVOS_AJUSTE: Final[Dict[str, str]] = {
    '0000': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0001': 'Pagamento/devolução de vendas pendentes de liquidação pela Cielo',
    '0002': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0003': 'Outros acertos',
    '0004': 'Cobrança de plano Cielo',
    '0005': 'Cobrança/devolução referente ao desconto incorreto da taxa administrativa de venda (MDR)',
    '0006': 'Outros acertos',
    '0007': 'Crédito/débito de valores rejeitados',
    '0008': 'Pagamento/devolução para correção de venda efetuada fora do prazo de pagamento',
    '0009': 'Pagamento/devolução de crédito temporário disponibilizado em análise de processo financeiro',
    '0010': 'Regularização de pagamento de vendas pendentes ao estabelecimento comercial',
    '0011': 'Valores não reconhecidos',
    '0012': 'Pagamento/devolução de crédito não realizado',
    '0013': 'Duplicidade referente Visa cash',
    '0014': 'Reenvio de débito não cumprido pelo banco anteriormente',
    '0015': 'Pagamento/devolução de crédito agendado ao estabelecimento comercial não vinculado a atividades financeiras',
    '0016': 'Negociação com área de prevenção',
    '0017': 'Pagamento/devolução de valor não efetuado dentro do prazo de pagamento',
    '0018': 'Pagamento/devolução referente ao cancelamento de antecipação',
    '0019': 'Pagamento/devolução de acertos diversos',
    '0020': 'Valores não processados',
    '0021': 'Crédito/débito de acerto ref. Valor debitado em conta-corrente',
    '0022': 'Cobrança/devolução de duplicidade de processamento do vale pedágio',
    '0023': 'Reenvio de crédito/débito não cumprido pelo banco',
    '0024': 'Pagamento/devolução do serviço de recarga de celular',
    '0025': 'Pagamento/devolução de valor não recebido devido a divergência nos dados bancários',
    '0026': 'Devolução de valores creditados/debitados indevidamente',
    '0027': 'Crédito/débito de transação eléctron não processada',
    '0028': 'Ajuste a Crédito/débito para antecipação/repasse',
    '0029': 'Regularização de pagamento de vendas pendentes ao estabelecimento comercial',
    '0030': 'Ajuste transação crediário/construcard',
    '0031': 'Cobrança/devolução de dívida negociada com o estabelecimento comercial',
    '0032': 'Estorno de débito/crédito ref. a acerto de duplicidade de crédito',
    '0033': 'Pagamento antecipação',
    '0034': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0035': 'Regularização de pagamento de antecipação de recebíveis pré-07/06/2021',
    '0036': 'Crédito/débito de transação eléctron real não processada',
    '0037': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0038': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0039': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0040': 'Reprocessamento transação eléctron',
    '0041': 'Transação agronegócio-custeio',
    '0042': 'Cobrança/devolução do produto de financiamento Agro Custeio - Banco do Brasil',
    '0043': 'Crédito/débito de venda com cartão de débito Bradesco',
    '0044': 'Crédito/débito cessão de direito agenda a vista',
    '0045': 'Crédito/débito de transação eléctron',
    '0046': 'Cobrança/devolução de venda não processada',
    '0047': 'Regularização de pagamento de vendas pendentes ao estabelecimento comercial',
    '0048': 'Reenvio de antecipação rejeitada',
    '0049': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0050': 'Estorno de reversão pagamento duplicidade - ARV',
    '0051': 'Premiação Visa',
    '0052': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0053': 'Troco fácil',
    '0054': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0055': 'Webservice boleto',
    '0056': 'Crédito referente parcelas antecipadas (pré-balcão)',
    '0057': 'Reembolso de CMPF',
    '0058': 'Crédito/débito ref. parcelas antecipadas',
    '0059': 'Cobrança/devolução da tarifa do extrato papel',
    '0060': 'Cobrança/devolução de mensalidade retroativa de aluguel da máquina Cielo',
    '0061': 'Cobrança diferença de plano Cielo',
    '0062': 'Plano Cielo - Pin Pads',
    '0063': 'Cobrança/devolução da mensalidade do aluguel da máquina Cielo',
    '0064': 'Débito venda autorização negada',
    '0065': 'Cobrança/devolução da mensalidade do aluguel da máquina Cielo',
    '0066': 'Plano Cielo - correspondente bancário',
    '0067': 'Plano Cielo - TEF discado',
    '0068': 'Desconto plano Cielo - cobrança direta',
    '0069': 'Plano Cielo - TEF IP',
    '0070': 'Desconto comercial sobre taxa',
    '0071': 'Cobrança/devolução da tarifa de cadastro',
    '0072': 'Aluguel de equipamento',
    '0073': 'Tarifa de cadastro',
    '0074': 'Crédito/débito promoção paixão por futebol Visa',
    '0075': 'Crédito/débito concessionaria',
    '0076': 'Crédito/débito arrecadador',
    '0077': 'Crédito/débito emissor',
    '0078': 'Tarifa de consulta transação AVS',
    '0079': 'Repasse de tarifa transação AVS',
    '0080': 'Crédito/débito cessão de recebíveis de venda parcelada',
    '0081': 'Crédito/débito de tarifa ref. Envio de bobina',
    '0082': 'Crédito/débito de tarifa ref. Envio de extrato papel',
    '0083': 'Crédito/débito de tarifa ref. Visita de manutenção POS',
    '0084': 'Ajuste a crédito/débito transação Flex Car',
    '0085': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0086': 'Créditos diversos Flex Car',
    '0087': 'Débitos diversos Flex Car',
    '0088': 'Webservice antifraude sem BPO',
    '0089': 'Webservice antifraude com BPO',
    '0090': 'Estorno/reprocessamento transação eléctron troco fácil',
    '0091': 'Transação saque troco fácil',
    '0092': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0093': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0094': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0095': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0096': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0097': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0098': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0099': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0100': 'Estorno cancelamento de venda via terminal parcelado loja',
    '0101': 'Crédito/débito ref. A erro no cadastramento da moeda',
    '0102': 'Regularização de pagamento de vendas pendentes ao estabelecimento comercial',
    '0103': 'Crédito/débito de valores complementares',
    '0104': 'Cobrança/estorno de aluguel de terminais eletrônicos',
    '0105': 'Crédito/débito de taxa de comissão',
    '0106': 'Crédito/débito referente a valores contestados pelo portador através do banco emissor',
    '0107': 'Débito/crédito por pagamentos de valores rejeitados Visa cash',
    '0108': 'Correção monetária',
    '0109': 'Crédito/débito temporário - processo em análise',
    '0110': 'Valores não processados',
    '0111': 'Pagamento em conta-corrente divergente',
    '0112': 'Crédito/débito ref. A pagamento em conta-corrente divergente',
    '0113': 'Outros acertos',
    '0114': 'Débito/estorno não cumprido',
    '0115': 'Pagamento/devolução de valor por acordo jurídico',
    '0116': 'Tarifa/estorno 2 via extrato papel',
    '0117': 'Reenvio de Crédito/estorno não cumprido pelo bco - ARV',
    '0118': 'Estorno de débito referente à vendas Cielo Promo',
    '0119': 'Acertos diversos',
    '0120': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0121': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0125': 'Crédito/débito referente produto seguro',
    '0126': 'Webservice recorrência inteligente',
    '0127': 'Crédito/débito referente a valores contestados pelo portador através do banco emissor',
    '0128': 'Crédito/débito referente a valores contestados pelo portador através do banco emissor',
    '0129': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0130': 'Webservice pacote',
    '0131': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0132': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0133': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0134': 'Acerto de recarga dinheiro e parceiros para o M4U',
    '0135': 'Cessão de direitos',
    '0136': 'Estorno/reenvio de débito não cumprido',
    '0137': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0138': 'Webservice boleto',
    '0139': 'Cobrança/devolução referente ao plano Cielo Controle',
    '0140': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0141': 'Outros acertos',
    '0142': 'Transferência de valores entre estabelecimentos da mesma raiz de CNPJ para compensação de saldo',
    '0143': 'Crédito/débito agro custeio',
    '0144': 'Cobrança/devolução referente ao plano Cielo Controle',
    '0145': 'Transferência de valores do dev. banco',
    '0149': 'Cobrança/devolução de parcela do Receba Mais',
    '0150': 'Cobrança/devolução da tarifa de aquisição de recebíveis via central de atendimento',
    '0151': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0152': 'Transação não processada',
    '0153': 'Pagamento/devolução sobre acordo jurídico',
    '0154': 'Confiança Cielo',
    '0155': 'Contrato de caução',
    '0156': 'Cobrança de multa da bandeira Mastercard por excesso de vendas contestadas',
    '0157': 'Cobrança/devolução de aluguel por não atingimento de meta de faturamento (Cielo Livre)',
    '0158': 'Pagamento/devolução de comissão periódica',
    '0159': 'Pagamento/devolução de comissão periódica',
    '0160': 'Cobrança de mensalidade de aluguel da máquina Cielo',
    '0161': 'Cobrança/estorno aluguel de terminais eletrônicos para férias e eventos',
    '0162': 'Cobrança/estorno aluguel de terminais eletrônicos C.C.C.',
    '0163': 'Cobrança/estorno aluguel de terminais eletrônicos C.S.C.',
    '0164': 'Cobrança/estorno aluguel de terminais eletrônicos (leitor de trilha)',
    '0165': 'Cobrança/estorno aluguel de terminais eletrônicos',
    '0166': 'Cobrança indevida',
    '0167': 'Pagamento/devolução de comissão periódica',
    '0168': 'Pagamento/devolução de comissão periódica',
    '0169': 'POS incentivado',
    '0170': 'Estorno/desconto comercial sobre taxa de desconto',
    '0171': 'Desconto comercial sobre taxa de desconto eléctron',
    '0172': 'Desconto comercial sobre taxa desconto - parcelado',
    '0173': 'Pagamento de incentivo emissores faturamento eléctron',
    '0174': 'Repasse de multa de bandeira por não conformidade',
    '0175': 'Cobrança/devolução de taxa do receba rápido',
    '0176': 'Ação promocional de Cashback',
    '0177': 'Transferência de valores entre estabelecimentos da mesma raiz de CNPJ para compensação de saldo',
    '0178': 'Fullcommerce - Velocity',
    '0179': 'Reprocessamento transação carnê',
    '0180': 'Fullcommerce - conciliador',
    '0181': 'Antifraude automático',
    '0182': 'Antifraude Advanced',
    '0183': 'Fullcommerce cartão protegido',
    '0184': 'Fullcommerce - gateway',
    '0185': 'Antifraude - manual',
    '0186': 'Antifraude Enterprise',
    '0188': 'Cobrança fee Copuneria',
    '0189': 'Crédito/débito Copuneria',
    '0190': 'Compensação de valores pendentes',
    '0191': 'Crédito/débito receba mais enviado c/c',
    '0192': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0193': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0194': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0195': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0196': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0197': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0198': 'Receba rápido compensação entre estabelecimentos',
    '0199': 'Crédito/débito desenvolvedor Cielo lio',
    '0200': 'Desconto negociação',
    '0201': 'Cessão de direito eléctron pré-datado',
    '0202': 'Crédito/débito aceleração de Cessão de direito eléctron pré-datado',
    '0203': 'Antecipação de cessão',
    '0204': 'Transação carnê Bradesco',
    '0205': 'Reprocessamento transação carnê',
    '0206': 'Estorno cancelamento venda carnê',
    '0207': 'Cancelamento venda carnê',
    '0208': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0209': 'Pagamento/devolução de comissão periódica',
    '0210': 'Pagamento/devolução de comissão periódica',
    '0211': 'Pagamento/devolução de comissão periódica',
    '0212': 'Pagamento/devolução de comissão periódica',
    '0213': 'Pagamento/devolução de comissão periódica',
    '0214': 'Pagamento/devolução de comissão periódica',
    '0215': 'Pagamento/devolução de comissão periódica',
    '0216': 'Ajuste periódico de comissão',
    '0217': 'Ajuste periódico de comissão',
    '0218': 'Ajuste periódico de comissão',
    '0219': 'Anistia dívidas cliente varejo',
    '0220': 'Venda cancelada pelo estabelecimento comercial',
    '0222': 'Reembolso EC PP',
    '0224': 'Compensação entre bandeiras online',
    '0225': 'Painel meu negócio',
    '0238': 'Reenvio débito não cumprido pelo banco anteriormente',
    '0246': 'Crédito/débito referente a Velocity Check',
    '0251': 'Cobrança/devolução de multa da bandeira por excesso de retentativas de venda no mesmo cartão',
    '0252': 'Pagamento/devolução de valor efetuado via TED',
    '0253': 'Pagamento/devolução de valor efetuado via PIX',
    '0254': 'Tarifa da bandeira',
    '0255': 'Reembolso/cobrança transação garantida',
    '0256': 'Cobrança/devolução de taxa por pagamento efetuado via PIX',
    '0257': 'Cobrança/pagamento para regularizar operações de vendas PIX em agenda financeira',
    '0258': 'Cobrança/devolução de tarifa da bandeira por vendas contestadas',
    '0259': 'Divergência do valor da nota fiscal - compra de máquina',
    '0260': 'Outros acertos',
    '0261': 'Parceria eleve',
    '0262': 'Estorno boleto comodato Cielo',
    '0264': 'Cobrança/devolução da compra de máquina Cielo sem aluguel',
    '0265': 'Pagamento/devolução para correção de estorno indevido',
    '0267': 'Pagamento/devolução de estorno indevido',
    '0269': 'Pagamento/devolução para regularizar o processamento de parcelas pendentes',
    '0270': 'Pagamento/devolução de valor em aberto decorrente da antecipação de recebíveis',
    '0271': 'Outros acertos',
    '0272': 'Cobrança de pagamento indevido e/ou devolução de cobrança indevida relacionados ao saldo utilizado em negociações de recebíveis',
    '0273': 'Outros acertos',
    '0274': 'Cobrança/devolução de vendas pagas em duplicidade e/ou valor maior ao estabelecimento comercial',
    '0275': 'Ressarcimento de terminais_ recuperação de ativos',
    '0276': 'Outros acertos',
    '0277': 'Acerto ref. ao cancel/estorno do pedido de venda máquina',
    '0278': 'Outros acertos',
    '0279': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0280': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0281': 'Regularização de terminais não recuperados',
    '0282': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0283': 'Compensação de créditos/débitos',
    '0284': 'Compensação de crédito/débito na conta digital',
    '0285': 'Outros acertos',
    '0286': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0287': 'Ajuste de aluguel equipamentos inativos',
    '0288': 'Venda contestada pelo portador do cartão através do banco emissor',
    '0289': 'De/para número logico',
    '0290': 'Outros acertos',
    '0291': 'Cobrança/devolução de pagamento indevido ao estabelecimento comercial',
    '0292': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0293': 'Ajuste débito/crédito Facebook',
    '0294': 'Ajuste reembolso Facebook',
    '0295': 'Ajuste reembolso Facebook',
    '0296': 'Crédito voucher - Facebook Donation',
    '0297': 'Cobrança/devolução do valor da máquina que não foi devolvida pelo estabelecimento comercial',
    '0298': 'Cobrança/devolução de pagamento indevido ao estabelecimento comercial',
    '0299': 'Cobrança/devolução de multa por inconformidade com as regras da bandeira',
    '0300': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0301': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0302': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0303': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0304': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0305': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0306': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0307': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0308': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0309': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0310': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0311': 'Transação acima do limite sem código de autorização',
    '0312': 'Transação em duplicidade',
    '0313': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0314': 'Transação com número do cartão inexistente',
    '0315': 'Cobrança/devolução decorrente do intercâmbio sobre vendas',
    '0316': 'Transação com número do cartão inexistente',
    '0317': 'Estorno de débito efetuado em transação realizada com chip',
    '0318': 'Estorno de débito efetuado em transação realizado com chip',
    '0320': 'Tarifa/estorno de multa programa monitoria chargeback',
    '0321': 'Transação acima do limite sem código de autorização',
    '0322': 'Venda em duplicidade',
    '0323': 'Crédito por envio do comprovante',
    '0324': 'Pagamento/devolução de valor pré-negociado com o estabelecimento à vista',
    '0325': 'Outros acertos',
    '0326': 'Venda desmembrada em mais de um comprovante',
    '0327': 'Assinatura divergente - portador não efetuou compra',
    '0328': 'Pré-arbitragem/pré-compliance',
    '0329': 'Pré-arbitragem/pré-compliance negociados parcelado',
    '0330': 'Cobrança/devolução de multa do programa monitoria das bandeiras',
    '0331': 'Transação acima do limite sem código de autorização',
    '0332': 'Venda em duplicidade não comprovada',
    '0333': 'Envio do comprovante pelo estabelecimento',
    '0334': 'Venda com número de cartão existente',
    '0335': 'Crédito/débito referente análise de intercambio',
    '0336': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0337': 'Processos de mediação',
    '0338': 'Cobrança/devolução de vendas pagas em duplicidade e/ou valor maior ao estabelecimento comercial',
    '0339': 'Cobrança/devolução de cancelamento que não foi efetuado na data da venda',
    '0340': 'Pagamento/devolução para correção relacionados a cancelamentos de vendas',
    '0341': 'Outros acertos',
    '0342': 'Pagamento/devolução de comissão periódica',
    '0343': 'Cobrança/devolução de valores pagos em confiança',
    '0344': 'Cobrança/devolução referente à contestação de débito em conta efetuado pelo banco',
    '0345': 'Cobrança/devolução do serviço Renova Fácil/ ABU Mastercard',
    '0346': 'Cobrança/devolução referente a venda cancelada que foi paga ao estabelecimento comercial',
    '0347': 'Cobrança/devolução de venda indevidamente paga ao estabelecimento comercial em antecipações/garantias',
    '0348': 'Cobrança/devolução de multa do programa monitoria das bandeiras',
    '0349': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0350': 'Estabelecimento Special Handling',
    '0351': 'Venda com código de autorização',
    '0352': 'Contestação da negociação de recebíveis',
    '0353': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0354': 'Acerto de débito em duplicidade',
    '0356': 'Portador não reconhece valor parcial da venda.',
    '0357': 'Intercambio referente a contestação do portador',
    '0358': 'Venda contestada pelo banco a pedido do portador do cartão',
    '0359': 'Irregularidade na transação',
    '0360': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0361': 'Chargeback transação débito - bandeira elo',
    '0362': 'Chargeback transação parcelado - bandeira elo',
    '0363': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0364': 'Devolução de cobrança contestada da bandeira Elo pelo estabelecimento comercial',
    '0365': 'Intercambio ref. contestação do portado',
    '0366': 'Análise de intercambio',
    '0367': 'Envio do comprovante pelo estabelecimento',
    '0368': 'Transação apresentada dentro do prazo contratual (intercambio)',
    '0369': 'Envio do comprovante pelo estabelecimento',
    '0370': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0371': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0372': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0373': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0374': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0375': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0376': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0377': 'Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor',
    '0378': 'Pagamento/devolução de débito duplicado na conta do estabelecimento comercial',
    '0379': 'Cobrança/devolução para corrigir vendas antecipadas duplicadas',
    '0380': 'Crédito/débito crediário Visa',
    '0381': 'Cobrança/devolução para regularização de recebíveis de outras adquirentes antecipados com a Cielo',
    '0382': 'Correção de crédito indevido para CPF/CNPJ',
    '0383': 'Correção de venda cobrada indevidamente do estabelecimento comercial em antecipações/garantias',
    '0384': 'Cobrança/devolução de vendas pagas em duplicidade e/ou valor maior ao estabelecimento comercial',
    '0385': 'Outros acertos',
    '0386': 'Pagamento/devolução para abater divergência entre valor devido e liquidado',
    '0387': 'Cobrança/devolução de pagamento indevido ao estabelecimento comercial',
    '0388': 'Ajuste referente ordem de pagamento',
    '0389': 'Crédito/débito referente a reversão de débito por cartão inexistente',
    '0391': 'Regularização de pagamento de vendas pendentes ao estabelecimento comercial',
    '0392': 'Outros acertos',
    '0393': 'Regularização de pagamento de vendas pendentes ao estabelecimento comercial',
    '0394': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0396': 'Crédito/débito devido a erro de sistema',
    '0397': 'Erro no processamento da venda',
    '0399': 'Ajuste a Crédito/débito por comprovante de venda legível/ilegível',
    '0400': 'Copia não atendida',
    '0401': 'Copia ilegível',
    '0402': 'Copia incorreta',
    '0403': 'Envio de documentos comprobatórios da venda',
    '0404': 'Outros acertos',
    '0408': 'Outros acertos',
    '0409': 'Crédito/débito transações parceladas negociadas com a Visanet',
    '0410': 'Valores negociados',
    '0411': 'Cashback - aluguel',
    '0412': 'Pagamento/devolução de cashback previsto na agenda financeira',
    '0413': 'Cobrança sobre venda paga a maior/em duplicidade ao estabelecimento comercial',
    '0414': 'Cobrança/devolução de pagamento indevido na conta do estabelecimento comercial por ocorrência sistêmica',
    '0415': 'Cobrança/devolução de vendas pagas em duplicidade e/ou valor maior ao estabelecimento comercial',
    '0416': 'Ajuste de vendas indevidas Amex, Hiper e JCB',
    '0417': 'Ajuste de vendas indevidas Amex, Hiper e JCB',
    '0418': 'Outros acertos',
    '0419': 'Outros acertos',
    '0421': 'Planos e serviços e-commerce',
    '0422': 'Planos e serviços e-commerce',
    '0423': 'Planos e serviços e-commerce',
    '0424': 'Planos e serviços e-commerce',
    '0425': 'Cobrança/devolução do serviço consulta Bin',
    '0426': 'Cobrança/devolução do serviço de verificação de cartão',
    '0427': 'Outros acertos',
    '0428': 'Devolução de cessão indevida',
    '0429': 'Cobrança/devolução de recebimento de operação com prejuízo financeiro',
    '0430': 'Cobrança/devolução do serviço de retentativas de vendas Cielo',
    '0431': 'Pagamento/devolução da campanha acesse e ganhe',
    '0432': 'Cobrança/devolução da mensalidade do Cielo Conciliador',
    '0434': 'Outros acertos',
    '0435': 'Pagamento/devolução referente ao incentivo de antecipação',
    '0436': 'Pagamento/devolução de crédito da campanha faturou e ganhou - cashback',
    '0437': 'Pagamento/devolução de cashback da campanha vendeu, ganhou',
    '0439': 'Cobrança/devolução de tarifa da bandeira por vendas não processadas',
    '0440': 'Cobrança/Devolução de interchange plus',
    '0441': 'Cobrança/devolução de pagamento indevido na conta do estabelecimento comercial por ocorrência sistêmica',
    '0442': 'Pagamento/devolução de valores de vendas devido ao estabelecimento comercial, em decorrência do status de inconformidade com as regras da bandeira',
    '0443': 'Ressarcimento de correção monetária sobre pagamentos das vendas fora do prazo',
    '0445': 'Cobrança sobre saldo reestabelecido ao estabelecimento comercial na conta de pagamento do Banco do Brasil',
    '0446': 'Cobrança de venda paga em duplicidade ao estabelecimento comercial por ocorrência sistêmica',
    '0447': 'Cobrança sobre saldo reestabelecido ao estabelecimento comercial na conta de pagamento do Banco Bradesco',
    '0448': 'Cobrança/devolução para regularização de recebíveis de outras adquirentes antecipados com a Cielo',
    '0449': 'Pagamento/devolução de valor indevido na conta do estabelecimento comercial por ocorrência sistêmica',
    '0450': 'Cobrança/devolução de multa por atraso no pagamento com a Cielo',
    '0452': 'Crédito/débito referente a valores contestados pelo portador através do banco emissor',
    '0453': 'Crédito/débito referente a valores contestados pelo portador através do banco emissor',
    '0454': 'Crédito/débito referente a valores contestados pelo portador através do banco emissor',
    '0459': 'Ressarcimento de correção monetária sobre pagamentos das vendas fora do prazo',
    '0460': 'Cobrança para regularização de valores em aberto do estabelecimento com a Cielo no Banco do Brasil',
    '0461': 'Ressarcimento de correção monetária sobre pagamentos das vendas fora do prazo',
    '0462': 'Cobrança para regularização de valores em aberto do estabelecimento com a Cielo no Banco Bradesco',
    '0463': 'Cobrança/devolução consumo do serviço renova fácil',
    '0464': 'Cobrança/devolução da mensalidade do aluguel da máquina Cielo',
    '0465': 'Estorno/Cobrança de aluguel de máquinas excedentes',
    '0467': 'Repasse de cobrança conforme novo programa monitoração (bandeira MasterCard)',
    '0468': 'Cashback devido alcance de meta de faturamento de máquinas em Cielo Facilita',
    '0469': 'Repasse/Devolução da tarifa de não tokenização Visa',
    '0470': 'Devolução da mensalidade do aluguel da máquina Cielo',
    '0471': 'Devolução da compra de máquina Cielo sem aluguel',
    '0488': 'Cobrança/devolução de tarifa da bandeira por arbitragem em vendas contestadas',
    '0508': 'Juros e correção monetária',
    '0510': 'Valores não processados',
    '0512': 'Pagamento em conta-corrente divergente',
    '0515': 'Acordo jurídico',
    '0517': 'Reenvio de crédito não cumprido pelo banco anteriormente',
    '0521': 'Estorno/débito de reversão de lançamento a débito (baixa forcada)',
    '0522': 'Lançamento a crédito baixa forcada',
    '0523': 'Transferência de valores entre estabelecimentos da mesma raiz de CNPJ para compensação de saldo',
    '0524': 'Devolução de lançamento de venda para ajustar o saldo em uma nova data',
    '0528': 'Acerto de cobrança',
    '0529': 'Pagamento de incentivo ao EC',
    '0530': 'Acerto autorizado pela Cielo',
    '0540': 'Estorno de reversão de crédito',
    '0541': 'Cobrança/devolução para correção de débito indevido ao estabelecimento comercial',
    '0542': 'Cobrança/devolução de dívida negociada com o estabelecimento comercial',
    '0548': 'Valores pendentes',
    '0549': 'Reversão de aluguel de POS',
    '0550': 'Valores suspensos',
    '0558': 'Acerto por tarifa anteriormente cancelada',
    '0560': 'Acerto referente a acordo comercial',
    '0601': 'Acerto de valores não processados',
    '0602': 'Acerto referente a regularização de data de pagamento',
    '0603': 'Acerto de valores complementares',
    '0604': 'Acerto de taxa de comissão',
    '0605': 'Crédito/débito referente a valores contestados',
    '0606': 'Correção monetária',
    '0607': 'Débito/estorno de débito de valores não reconhecidos',
    '0608': 'Crédito/débito referente a pagamento em conta-corrente divergente',
    '0609': 'Reenvio de crédito não cumprido pelo banco anteriormente',
    '0610': 'Acerto de valores não processados',
    '0611': 'Acerto referente acerto de duplicidade',
    '0613': 'Estorno cancelamento de venda Alelo refeição',
    '0614': 'Crédito/débito de transação Alelo refeição não processada',
    '0615': 'Reenvio de antecipação rejeitada (pré-balcão)',
    '0616': 'Acerto referente a negociação com a área de prevenção',
    '0617': 'Tarifa operacional sobre créditos Alelo',
    '0618': 'POS incentivado',
    '0619': 'Acertos diversos',
    '0620': 'Estorno/tarifa operacional sobre créditos Alelo',
    '0621': 'Cancelamento de vendas (envio eletrônico)',
    '0622': 'Alelo desenvolvedores',
    '0623': 'Reversão de lançamento a Crédito/débito baixado manual',
    '0624': 'Reenvio tarifa TOR',
    '0625': 'Reenvio tarifa de manutenção Alelo',
    '0626': 'Estorno/cobrança de tarifa de cadastro Alelo',
    '0627': 'Tarifa mensal - Alelo na medida',
    '0628': 'Tarifa mensal - Alelo na medida',
    '0629': 'Crédito/débito de antecipação rejeitada',
    '0631': 'Estorno/reversão de lançamento a débito baixado manual',
    '0632': 'Reversão de lançamento a Crédito/débito baixado manualmente',
    '0633': 'Acerto ref. acerto de cobrança',
    '0634': 'Estorno/cobrança de débito de acordo de cobrança',
    '0635': 'Ajuste a Crédito/débito de valores pendentes',
    '0636': 'Crédito/débito referente a acerto de valores suspensos',
    '0637': 'Crédito/débito assinatura internet delivery Alelo',
    '0638': 'Crédito/débito referente a análise de intercambio cartão cultura',
    '0640': 'Outros acertos',
    '0641': 'Acerto a débito/crédito referente a negociação com área de prevenção',
    '0645': 'Acerto do bloqueio de valor por ordem judicial',
    '0648': 'Regularização de pagamento de vendas com status suspenso ao estabelecimento comercial',
    '0649': 'Programa Smiles',
    '0650': 'Crédito/estorno Smiles referente ao acúmulo de milhas',
    '0651': 'Crédito/estorno ao EC referente as milhas Smiles resgatadas',
    '0652': 'Programa Smiles',
    '0653': 'Pagamento/devolução de transação realizada via boleto bancário',
    '0661': 'Crédito/débito referente análise de intercambio refeição',
    '0680': 'Cobrança mensal e-lynx',
    '0700': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0713': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0714': 'Crédito/débito de transação Alelo alimentação não processadas',
    '0715': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0716': 'Transação Alelo não processada',
    '0720': 'Outros acertos',
    '0722': 'Pagamento/devolução de venda',
    '0745': 'Acerto Hipercard festa de são João',
    '0759': 'Cobrança Meliuz',
    '0760': 'Estorno Cobrança Meliuz',
    '0761': 'Crédito/débito referente a análise de intercambio alimentação',
    '0797': 'Cobrança/devolução de valores por compra de aplicativo no Cielo Store',
    '0798': 'Cobrança/devolução de valores por compra de aplicativo no Cielo Store',
    '0799': 'Cobrança/pagamento de receita sobre aplicativos Cielo Store',
    '0800': 'Pagamento/devolução sobre Cielo Store',
    '0810': 'Cobrança referente a antecipação de recebíveis',
    '0811': 'Serviço conciliador',
    '0812': 'Serviço gateway',
    '0813': 'Serviço cartão protegido',
    '0814': 'Cobrança/devolução do serviço antifraude',
    '0815': 'Serviço antifraude',
    '0817': 'Acerto cancelamento POS Alelo',
    '0819': 'Regularização de valores indevidos',
    '0825': 'Cobrança/devolução de tarifa por manutenção cadastral',
    '0879': 'Cobrança/devolução do Cielo Controle',
    '0882': 'Cobrança/devolução de mensalidade do Farol',
    '0883': 'Cobrança/devolução sobre alteração de plano do Farol',
    '0884': 'Cobrança/devolução do serviço de Big data',
    '0890': 'FCO giro via termina',
    '0891': 'Ajuste a crédito transação Capital de giro',
    '0892': 'Reversão cancelamento Capital de giro',
    '0893': 'Reversão/estorno cancelamento capital de giro via terminal',
    '0894': 'Ajuste a Crédito/débito trans. Crédito imobiliário',
    '0895': 'Reversão cancelamento crédito imobiliário',
    '0896': 'Cancelamento/reversão crédito imobiliário via terminal',
    '0898': 'Estorno/ cancelamento de venda produto crédito especializado',
    '0899': 'Estorno/ cancelamento de venda produto crédito especializado via terminal',
    '0901': 'Acerto Amex indevido',
    '0902': 'Tarifa de retentativas Master Card',
    '0910': 'Outros acertos',
    '0920': 'Comissão emissor internacional',
    '0950': 'Crédito/débito referente análise de intercambio refeição',
    '0951': 'Débito/crédito referente a análise de intercambio alimentação',
    '0952': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0953': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0954': 'Pagamento/devolução referente ao incentivo oferecido na conversão dinâmica de moeda (DCC)',
    '0959': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0960': 'Pagamento/devolução de incentivo comercial sobre o faturamento',
    '0961': 'Desconto comercial verba subsidiada pelo banco',
    '0962': 'Outros acertos',
    '0963': 'Desconto comercial verba subsidiada pelo banco',
    '0964': 'Transferência de valores entre estabelecimentos com a mesma raiz CNPJ para compensação de saldo',
    '0965': 'Transferência de valores entre estabelecimentos com a mesma raiz CNPJ para compensação de saldo',
    '0966': 'Outros acertos',
    '0967': 'Cobrança/devolução da taxa de antecipação de recebíveis',
    '0968': 'Acerto serviço de recarga',
    '0969': 'Cobrança/devolução referente à antecipação do benefício de redução de aluguel',
    '0971': 'Pagamento/devolução de comissão periódica',
    '0972': 'Crédito/débito referente a processo de "de/para" - comercial',
    '0973': 'Incentivo serviço Sky',
    '0974': 'Tarifa de cadastro Alelo',
    '0975': 'Repasse de cobrança do serviço Vivo Easy ao estabelecimento comercial',
    '0976': 'Cobrança/devolução da mensalidade do Cielo e-commerce - checkout',
    '0977': 'Desconto aluguel',
    '0979': 'Incentivo comercial',
    '0981': 'Aluguel máquina mobile "chip and pin"',
    '0982': 'Tarifa de manutenção Alelo',
    '0984': 'Cobrança/devolução de prejuízo, acidente ou dano ao equipamento',
    '0985': 'Ajuste a Crédito/débito transação FCO investimento',
    '0986': 'Reversão/cancelamento de transação FCO investimento',
    '0987': 'Reversão/cancelamento de transação FCO investimento via terminal',
    '0988': 'Ajuste a Crédito/débito de transação FCO giro',
    '0989': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0990': 'Crédito/débito contestação bens e serviços refeição',
    '0991': 'Cobrança/devolução de venda cancelada pelo estabelecimento comercial',
    '0992': 'Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial',
    '0995': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0996': 'Contestação de transação parcelada',
    '0997': 'Outros acertos',
    '0998': 'Cobrança/devolução de venda contestada pelo portador através do banco emissor',
    '0999': 'Outros acertos'
}


def get_descricao(tabela: Dict[str, str], codigo: str, default: str = "Não identificado") -> str:
    """
    Obtém a descrição de um código em uma tabela de domínio.

    Args:
        tabela: Dicionário com códigos e descrições
        codigo: Código a ser consultado
        default: Valor padrão se código não encontrado

    Returns:
        Descrição do código ou valor default
    """
    return tabela.get(codigo, default)
